export enum AppIcons {
  ICON_DELETE = 'fa fa-trash',
  ICON_REJECT = 'fa fa-minus-circle',
  ICON_APPROVE = 'fa fa-check',
  ICON_APPROVE_REJECT = 'fa fa-tasks',
  ICON_SKIP_APPROVAL = 'fa fa-step-forward',
  ICON_DETAIL_VIEW = 'fa fa-list-alt',
  ICON_COMMENT = 'pi pi-comment',
  ICON_CLONE = 'fa fa-clone',
  ICON_USE = 'fa fa-hand-o-up',
  ICON_PAY_NOW = 'pi pi-dollar',
  ICON_SUBMIT_FOE_APPROVAL = 'pi pi-check',
  ICON_AUDIT_TRAIL = 'fa fa-book',
  ICON_SPLIT = 'fa-solid fa-arrows-split-up-and-left fa-rotate-180',
  ICON_CANCEL = 'pi pi-times-circle',
  ICON_DOWNLOAD_BILL_FONT_AWESOME = 'fa fa-download',
  ICON_VIEW_SUMMARY = 'fa fa-file-text-o',
  ICON_UNDO_STATUS = 'fa fa-undo',
  ICON_RESEND_INVITATION = 'fa fa-paper-plane',
  ICON_VIEW_REPORT = 'fa fa-download',
  ICON_EDIT_RESUBMIT = 'fa fa-pencil',
  ICON_CLOSE = 'fa fa-times',
  ICON_OPEN = 'fa-regular fa-circle-check',
  ICON_MARK_AS_MAILED = 'fa fa-times',
  ICON_VOID_PAYMENT = 'fa fa-ban',
  ICON_CHANGE_BILL = 'fa fa fa-refresh',
  ICON_VIEW_BILL = 'fa fa-eye',
  ICON_DETAIL_REPORT = 'fa-solid fa-file-arrow-down',
  ICON_EDIT = 'fa fa-pencil',
  ICON_TOP_UP = 'fa-solid fa-arrows-up-to-line',
  ICON_DISCARD = 'fa fa-minus-square-o',
  ICON_ACTIVATE = 'fa fa-toggle-on',
  ICON_INACTIVATE = 'fa fa-toggle-off',
  ICON_UNLOCK = 'fa fa-unlock',
  ICON_PASSWORD_RESET = 'pi pi-refresh',
  ICON_INACTIVE = 'fa fa-toggle-off',
  ICON_ACTIVE = 'fa fa-toggle-on',
  ICON_APPLIED_PAYMENTS = 'fa fa-usd',
  ICON_PAYMENT_PROCESS = 'fa fa-credit-card',
  ICON_ADD_TO_LOCAL = 'pi pi-plus',
  ICON_ATTACH_TO_DOCUMENT = 'pi pi-paperclip',
  ICON_CHANGE_ASSIGNEE = 'fa fa-share-alt',
  ICON_SEND_APPROVAL = 'pi pi-reply',
  ICON_EXPORT = 'fa fa-share',
  ICON_VIEW_ATTACHED_BILL = 'fa fa-expand',
  BILL_ICON = 'fa fa-file-text',
  PURCHASE_ORDER_ICON = 'fa fa-cart-arrow-down',
  PURCHASE_ORDER_RECEIPT_ICON = 'fa fa-usd',
  AUTOMATION_ICON = 'fa fa-tasks',
  EXPENSE_ICON = 'fa fa-usd',
  CREDIT_CARD_ICON = 'pi pi-credit-card',
  RECEIPT_ICON = 'pi pi-book',
  PAYMENT_ICON = 'fa fa-credit-card',
  VENDOR_ICON = 'pi pi-users',
  RECOVER_ICON = 'fa fa-undo',
  SEND_ICON = 'fa-solid fa-paper-plane',

  ICON_PAYMENT_OFFLINE_PROCESS = 'fa fa-link',
  ICON_PAYMENT_UNDO_OFFLINE_PROCESS ='fa fa-chain-broken',

  MARK_AS_PAID_ICON = 'pi pi-dollar',
  MARK_AS_UNPAID_ICON = 'pi pi-undo',


}
