export enum AppDocuments {
  DOCUMENT_EVENT_SUBMITTED = 1,
  DOCUMENT_EVENT_EDIT_RESUBMIT = 2,
  DOCUMENT_EVENT_APPROVED = 3,
  DOCUMENT_EVENT_REJECTED = 4,
  DOCUMENT_EVENT_SKIP_APPROVAL = 5,
  DOCUMENT_EVENT_DELETED = 6,
  DOCUMENT_EVENT_SEND_TO_VENDOR = 7,
  DOCUMENT_EVENT_CREATED = 8,
  DOCUMENT_EVENT_UPLOADED = 9,
  DOCUMENT_EVENT_REASSIGNED = 10,
  DOCUMENT_EVENT_VOID = 11,
  DOCUMENT_EVENT_MARK_AS_MAILED = 12,
  DOCUMENT_EVENT_APPLY_TO_DIFFERENT_BILL = 13,
  DOCUMENT_EVENT_PAY_NOW = 14,
  DOCUMENT_EVENT_EDIT = 37

}
