export enum AppAutomationAction {

  CREATE_APPROVAL_WORKFLOW = 1,
  SEND_EMAIL_NOTIFICATION = 2,
  SEND_USER_NOTIFICATION = 3,
  SET_FIELD_VALUE = 4,
  EXECUTE_AUTOMATION = 5,
  SYNC_WITH_THIRD_PART_APPLICATION = 6,
  ASSIGN_TO = 7,
  FINAL_APPROVE = 8,

}
