export enum AppReportType {

  CASH_REQUIREMENT_REPORT = 1,
  VENDOR_DETAIL_REPORT = 2,
  USER_OVERVIEW_REPORT = 3,
  AP_DETAIL_REPORT = 4,
  AP_AGING_SUMMARY_BY_VENDOR_REPORT = 5,
  AP_AGING_SUMMARY_BY_USER_REPORT = 6,
  PO_BY_DEPARTMENT_REPORT = 7,
  PO_OUTSTANDING_REPORT = 8,
  EXPENSE_BY_CUSTOM_FIELD_REPORT = 9,
  EXPENSES_BY_ACCOUNT_SUMMARY = 10,
  EXPENSES_BY_ACCOUNT_DETAILS = 11,
  TRANSACTIONS_AWAITING_APPROVAL = 12,
  PROJECT_PO_SUMMARY_REPORT = 13,
  PO_RECEIPT_DETAIL_REPORT = 14,
  BILLABLE_TRANSACTIONS= 15,
  AP_BILL_DETAILS_REPORT= 16,
}
