export enum AppAdditionalFieldValidation {

  VALIDATION_NAME = 1,
  VALIDATION_DISPLAY_ORDER = 2,
  VALIDATION_REQUIRED = 3,
  VALIDATION_MAX_LENGTH = 4,
  VALIDATION_DATA_TYPE = 5,
  VALIDATION_MULTIPLE_CREATE_NEW = 6,
  VALIDATION_DATA_SOURCE = 7,
  VALIDATIONS_ACCEPT = 8,
  VALIDATIONS_ROWS = 9,
  VALIDATIONS_VALUE = 10,
  VALIDATION_OPTION = 11

}
