import {PoDetailDto} from './po-detail-dto';
import {AdHocWorkflowDetailConfig} from '../automation/adHoc-workflow-detail-config';
import {VpPoAdditionalfieldAttachments} from './vp-po-additionalfield-attachments';
import {AdditionalFieldDetailDto} from '../additional-field/additional-field-detail-dto';
import {PoAccountDetailDto} from './po-account-detail-dto';

export class PoMasterDto {

  public id: number;
  public poNumber: string;
  public poDate: any;
  public vendorId: number;
  public projectTask: number;
  public deliveryDate: any;
  public pocName: string;
  public pocPhone: number;
  public notes: string;
  public shippingAddress: string;
  public billingAddress: string;
  public grossAmount: number;
  public taxAmount: number;
  public attachmentId: number;
  public discountAmount: number;
  public netAmount: number;
  public automationId: number;
  public approvalGroup: string;
  public taxPercentageStr: string;
  public taxPercentage: any;
  public approvalUser: string;
  public noOfLevels: number;
  public workflowLevel: number;
  public workflowId: number;
  public approvedBy: string;
  public accountGrossAmount: number;
  public itemGrossAmount: number;
  public status: any;
  public attachments: File [] = new Array();
  public autoGeneratedPoNo = false;

  public extendedApprovalUser: string;

  public purchaseOrderDetails: PoDetailDto[] = [];
  public purchaseOrderAccountDetails: PoAccountDetailDto [] = [];
  public additionalData: AdditionalFieldDetailDto[] = new Array();
  public adHocWorkflowDetails: AdHocWorkflowDetailConfig[] = [];
  public additionalFieldAttachments: VpPoAdditionalfieldAttachments [] = [];

  public createdBy: string;

  public documentTypeId: number;
  public eventId: number;
  public remarks: string;


  public internalApprovalStatus: string;
  expenseAccountIdList = [];
  itemIdList = [];
}
